###################################################################

# Created by write_sdc on Tue Jun 16 03:53:26 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {out_data[215]}]
set_load -pin_load 0.05 [get_ports {out_data[214]}]
set_load -pin_load 0.05 [get_ports {out_data[213]}]
set_load -pin_load 0.05 [get_ports {out_data[212]}]
set_load -pin_load 0.05 [get_ports {out_data[211]}]
set_load -pin_load 0.05 [get_ports {out_data[210]}]
set_load -pin_load 0.05 [get_ports {out_data[209]}]
set_load -pin_load 0.05 [get_ports {out_data[208]}]
set_load -pin_load 0.05 [get_ports {out_data[207]}]
set_load -pin_load 0.05 [get_ports {out_data[206]}]
set_load -pin_load 0.05 [get_ports {out_data[205]}]
set_load -pin_load 0.05 [get_ports {out_data[204]}]
set_load -pin_load 0.05 [get_ports {out_data[203]}]
set_load -pin_load 0.05 [get_ports {out_data[202]}]
set_load -pin_load 0.05 [get_ports {out_data[201]}]
set_load -pin_load 0.05 [get_ports {out_data[200]}]
set_load -pin_load 0.05 [get_ports {out_data[199]}]
set_load -pin_load 0.05 [get_ports {out_data[198]}]
set_load -pin_load 0.05 [get_ports {out_data[197]}]
set_load -pin_load 0.05 [get_ports {out_data[196]}]
set_load -pin_load 0.05 [get_ports {out_data[195]}]
set_load -pin_load 0.05 [get_ports {out_data[194]}]
set_load -pin_load 0.05 [get_ports {out_data[193]}]
set_load -pin_load 0.05 [get_ports {out_data[192]}]
set_load -pin_load 0.05 [get_ports {out_data[191]}]
set_load -pin_load 0.05 [get_ports {out_data[190]}]
set_load -pin_load 0.05 [get_ports {out_data[189]}]
set_load -pin_load 0.05 [get_ports {out_data[188]}]
set_load -pin_load 0.05 [get_ports {out_data[187]}]
set_load -pin_load 0.05 [get_ports {out_data[186]}]
set_load -pin_load 0.05 [get_ports {out_data[185]}]
set_load -pin_load 0.05 [get_ports {out_data[184]}]
set_load -pin_load 0.05 [get_ports {out_data[183]}]
set_load -pin_load 0.05 [get_ports {out_data[182]}]
set_load -pin_load 0.05 [get_ports {out_data[181]}]
set_load -pin_load 0.05 [get_ports {out_data[180]}]
set_load -pin_load 0.05 [get_ports {out_data[179]}]
set_load -pin_load 0.05 [get_ports {out_data[178]}]
set_load -pin_load 0.05 [get_ports {out_data[177]}]
set_load -pin_load 0.05 [get_ports {out_data[176]}]
set_load -pin_load 0.05 [get_ports {out_data[175]}]
set_load -pin_load 0.05 [get_ports {out_data[174]}]
set_load -pin_load 0.05 [get_ports {out_data[173]}]
set_load -pin_load 0.05 [get_ports {out_data[172]}]
set_load -pin_load 0.05 [get_ports {out_data[171]}]
set_load -pin_load 0.05 [get_ports {out_data[170]}]
set_load -pin_load 0.05 [get_ports {out_data[169]}]
set_load -pin_load 0.05 [get_ports {out_data[168]}]
set_load -pin_load 0.05 [get_ports {out_data[167]}]
set_load -pin_load 0.05 [get_ports {out_data[166]}]
set_load -pin_load 0.05 [get_ports {out_data[165]}]
set_load -pin_load 0.05 [get_ports {out_data[164]}]
set_load -pin_load 0.05 [get_ports {out_data[163]}]
set_load -pin_load 0.05 [get_ports {out_data[162]}]
set_load -pin_load 0.05 [get_ports {out_data[161]}]
set_load -pin_load 0.05 [get_ports {out_data[160]}]
set_load -pin_load 0.05 [get_ports {out_data[159]}]
set_load -pin_load 0.05 [get_ports {out_data[158]}]
set_load -pin_load 0.05 [get_ports {out_data[157]}]
set_load -pin_load 0.05 [get_ports {out_data[156]}]
set_load -pin_load 0.05 [get_ports {out_data[155]}]
set_load -pin_load 0.05 [get_ports {out_data[154]}]
set_load -pin_load 0.05 [get_ports {out_data[153]}]
set_load -pin_load 0.05 [get_ports {out_data[152]}]
set_load -pin_load 0.05 [get_ports {out_data[151]}]
set_load -pin_load 0.05 [get_ports {out_data[150]}]
set_load -pin_load 0.05 [get_ports {out_data[149]}]
set_load -pin_load 0.05 [get_ports {out_data[148]}]
set_load -pin_load 0.05 [get_ports {out_data[147]}]
set_load -pin_load 0.05 [get_ports {out_data[146]}]
set_load -pin_load 0.05 [get_ports {out_data[145]}]
set_load -pin_load 0.05 [get_ports {out_data[144]}]
set_load -pin_load 0.05 [get_ports {out_data[143]}]
set_load -pin_load 0.05 [get_ports {out_data[142]}]
set_load -pin_load 0.05 [get_ports {out_data[141]}]
set_load -pin_load 0.05 [get_ports {out_data[140]}]
set_load -pin_load 0.05 [get_ports {out_data[139]}]
set_load -pin_load 0.05 [get_ports {out_data[138]}]
set_load -pin_load 0.05 [get_ports {out_data[137]}]
set_load -pin_load 0.05 [get_ports {out_data[136]}]
set_load -pin_load 0.05 [get_ports {out_data[135]}]
set_load -pin_load 0.05 [get_ports {out_data[134]}]
set_load -pin_load 0.05 [get_ports {out_data[133]}]
set_load -pin_load 0.05 [get_ports {out_data[132]}]
set_load -pin_load 0.05 [get_ports {out_data[131]}]
set_load -pin_load 0.05 [get_ports {out_data[130]}]
set_load -pin_load 0.05 [get_ports {out_data[129]}]
set_load -pin_load 0.05 [get_ports {out_data[128]}]
set_load -pin_load 0.05 [get_ports {out_data[127]}]
set_load -pin_load 0.05 [get_ports {out_data[126]}]
set_load -pin_load 0.05 [get_ports {out_data[125]}]
set_load -pin_load 0.05 [get_ports {out_data[124]}]
set_load -pin_load 0.05 [get_ports {out_data[123]}]
set_load -pin_load 0.05 [get_ports {out_data[122]}]
set_load -pin_load 0.05 [get_ports {out_data[121]}]
set_load -pin_load 0.05 [get_ports {out_data[120]}]
set_load -pin_load 0.05 [get_ports {out_data[119]}]
set_load -pin_load 0.05 [get_ports {out_data[118]}]
set_load -pin_load 0.05 [get_ports {out_data[117]}]
set_load -pin_load 0.05 [get_ports {out_data[116]}]
set_load -pin_load 0.05 [get_ports {out_data[115]}]
set_load -pin_load 0.05 [get_ports {out_data[114]}]
set_load -pin_load 0.05 [get_ports {out_data[113]}]
set_load -pin_load 0.05 [get_ports {out_data[112]}]
set_load -pin_load 0.05 [get_ports {out_data[111]}]
set_load -pin_load 0.05 [get_ports {out_data[110]}]
set_load -pin_load 0.05 [get_ports {out_data[109]}]
set_load -pin_load 0.05 [get_ports {out_data[108]}]
set_load -pin_load 0.05 [get_ports {out_data[107]}]
set_load -pin_load 0.05 [get_ports {out_data[106]}]
set_load -pin_load 0.05 [get_ports {out_data[105]}]
set_load -pin_load 0.05 [get_ports {out_data[104]}]
set_load -pin_load 0.05 [get_ports {out_data[103]}]
set_load -pin_load 0.05 [get_ports {out_data[102]}]
set_load -pin_load 0.05 [get_ports {out_data[101]}]
set_load -pin_load 0.05 [get_ports {out_data[100]}]
set_load -pin_load 0.05 [get_ports {out_data[99]}]
set_load -pin_load 0.05 [get_ports {out_data[98]}]
set_load -pin_load 0.05 [get_ports {out_data[97]}]
set_load -pin_load 0.05 [get_ports {out_data[96]}]
set_load -pin_load 0.05 [get_ports {out_data[95]}]
set_load -pin_load 0.05 [get_ports {out_data[94]}]
set_load -pin_load 0.05 [get_ports {out_data[93]}]
set_load -pin_load 0.05 [get_ports {out_data[92]}]
set_load -pin_load 0.05 [get_ports {out_data[91]}]
set_load -pin_load 0.05 [get_ports {out_data[90]}]
set_load -pin_load 0.05 [get_ports {out_data[89]}]
set_load -pin_load 0.05 [get_ports {out_data[88]}]
set_load -pin_load 0.05 [get_ports {out_data[87]}]
set_load -pin_load 0.05 [get_ports {out_data[86]}]
set_load -pin_load 0.05 [get_ports {out_data[85]}]
set_load -pin_load 0.05 [get_ports {out_data[84]}]
set_load -pin_load 0.05 [get_ports {out_data[83]}]
set_load -pin_load 0.05 [get_ports {out_data[82]}]
set_load -pin_load 0.05 [get_ports {out_data[81]}]
set_load -pin_load 0.05 [get_ports {out_data[80]}]
set_load -pin_load 0.05 [get_ports {out_data[79]}]
set_load -pin_load 0.05 [get_ports {out_data[78]}]
set_load -pin_load 0.05 [get_ports {out_data[77]}]
set_load -pin_load 0.05 [get_ports {out_data[76]}]
set_load -pin_load 0.05 [get_ports {out_data[75]}]
set_load -pin_load 0.05 [get_ports {out_data[74]}]
set_load -pin_load 0.05 [get_ports {out_data[73]}]
set_load -pin_load 0.05 [get_ports {out_data[72]}]
set_load -pin_load 0.05 [get_ports {out_data[71]}]
set_load -pin_load 0.05 [get_ports {out_data[70]}]
set_load -pin_load 0.05 [get_ports {out_data[69]}]
set_load -pin_load 0.05 [get_ports {out_data[68]}]
set_load -pin_load 0.05 [get_ports {out_data[67]}]
set_load -pin_load 0.05 [get_ports {out_data[66]}]
set_load -pin_load 0.05 [get_ports {out_data[65]}]
set_load -pin_load 0.05 [get_ports {out_data[64]}]
set_load -pin_load 0.05 [get_ports {out_data[63]}]
set_load -pin_load 0.05 [get_ports {out_data[62]}]
set_load -pin_load 0.05 [get_ports {out_data[61]}]
set_load -pin_load 0.05 [get_ports {out_data[60]}]
set_load -pin_load 0.05 [get_ports {out_data[59]}]
set_load -pin_load 0.05 [get_ports {out_data[58]}]
set_load -pin_load 0.05 [get_ports {out_data[57]}]
set_load -pin_load 0.05 [get_ports {out_data[56]}]
set_load -pin_load 0.05 [get_ports {out_data[55]}]
set_load -pin_load 0.05 [get_ports {out_data[54]}]
set_load -pin_load 0.05 [get_ports {out_data[53]}]
set_load -pin_load 0.05 [get_ports {out_data[52]}]
set_load -pin_load 0.05 [get_ports {out_data[51]}]
set_load -pin_load 0.05 [get_ports {out_data[50]}]
set_load -pin_load 0.05 [get_ports {out_data[49]}]
set_load -pin_load 0.05 [get_ports {out_data[48]}]
set_load -pin_load 0.05 [get_ports {out_data[47]}]
set_load -pin_load 0.05 [get_ports {out_data[46]}]
set_load -pin_load 0.05 [get_ports {out_data[45]}]
set_load -pin_load 0.05 [get_ports {out_data[44]}]
set_load -pin_load 0.05 [get_ports {out_data[43]}]
set_load -pin_load 0.05 [get_ports {out_data[42]}]
set_load -pin_load 0.05 [get_ports {out_data[41]}]
set_load -pin_load 0.05 [get_ports {out_data[40]}]
set_load -pin_load 0.05 [get_ports {out_data[39]}]
set_load -pin_load 0.05 [get_ports {out_data[38]}]
set_load -pin_load 0.05 [get_ports {out_data[37]}]
set_load -pin_load 0.05 [get_ports {out_data[36]}]
set_load -pin_load 0.05 [get_ports {out_data[35]}]
set_load -pin_load 0.05 [get_ports {out_data[34]}]
set_load -pin_load 0.05 [get_ports {out_data[33]}]
set_load -pin_load 0.05 [get_ports {out_data[32]}]
set_load -pin_load 0.05 [get_ports {out_data[31]}]
set_load -pin_load 0.05 [get_ports {out_data[30]}]
set_load -pin_load 0.05 [get_ports {out_data[29]}]
set_load -pin_load 0.05 [get_ports {out_data[28]}]
set_load -pin_load 0.05 [get_ports {out_data[27]}]
set_load -pin_load 0.05 [get_ports {out_data[26]}]
set_load -pin_load 0.05 [get_ports {out_data[25]}]
set_load -pin_load 0.05 [get_ports {out_data[24]}]
set_load -pin_load 0.05 [get_ports {out_data[23]}]
set_load -pin_load 0.05 [get_ports {out_data[22]}]
set_load -pin_load 0.05 [get_ports {out_data[21]}]
set_load -pin_load 0.05 [get_ports {out_data[20]}]
set_load -pin_load 0.05 [get_ports {out_data[19]}]
set_load -pin_load 0.05 [get_ports {out_data[18]}]
set_load -pin_load 0.05 [get_ports {out_data[17]}]
set_load -pin_load 0.05 [get_ports {out_data[16]}]
set_load -pin_load 0.05 [get_ports {out_data[15]}]
set_load -pin_load 0.05 [get_ports {out_data[14]}]
set_load -pin_load 0.05 [get_ports {out_data[13]}]
set_load -pin_load 0.05 [get_ports {out_data[12]}]
set_load -pin_load 0.05 [get_ports {out_data[11]}]
set_load -pin_load 0.05 [get_ports {out_data[10]}]
set_load -pin_load 0.05 [get_ports {out_data[9]}]
set_load -pin_load 0.05 [get_ports {out_data[8]}]
set_load -pin_load 0.05 [get_ports {out_data[7]}]
set_load -pin_load 0.05 [get_ports {out_data[6]}]
set_load -pin_load 0.05 [get_ports {out_data[5]}]
set_load -pin_load 0.05 [get_ports {out_data[4]}]
set_load -pin_load 0.05 [get_ports {out_data[3]}]
set_load -pin_load 0.05 [get_ports {out_data[2]}]
set_load -pin_load 0.05 [get_ports {out_data[1]}]
set_load -pin_load 0.05 [get_ports {out_data[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports {in_data[71]}]
set_max_capacitance 0.15 [get_ports {in_data[70]}]
set_max_capacitance 0.15 [get_ports {in_data[69]}]
set_max_capacitance 0.15 [get_ports {in_data[68]}]
set_max_capacitance 0.15 [get_ports {in_data[67]}]
set_max_capacitance 0.15 [get_ports {in_data[66]}]
set_max_capacitance 0.15 [get_ports {in_data[65]}]
set_max_capacitance 0.15 [get_ports {in_data[64]}]
set_max_capacitance 0.15 [get_ports {in_data[63]}]
set_max_capacitance 0.15 [get_ports {in_data[62]}]
set_max_capacitance 0.15 [get_ports {in_data[61]}]
set_max_capacitance 0.15 [get_ports {in_data[60]}]
set_max_capacitance 0.15 [get_ports {in_data[59]}]
set_max_capacitance 0.15 [get_ports {in_data[58]}]
set_max_capacitance 0.15 [get_ports {in_data[57]}]
set_max_capacitance 0.15 [get_ports {in_data[56]}]
set_max_capacitance 0.15 [get_ports {in_data[55]}]
set_max_capacitance 0.15 [get_ports {in_data[54]}]
set_max_capacitance 0.15 [get_ports {in_data[53]}]
set_max_capacitance 0.15 [get_ports {in_data[52]}]
set_max_capacitance 0.15 [get_ports {in_data[51]}]
set_max_capacitance 0.15 [get_ports {in_data[50]}]
set_max_capacitance 0.15 [get_ports {in_data[49]}]
set_max_capacitance 0.15 [get_ports {in_data[48]}]
set_max_capacitance 0.15 [get_ports {in_data[47]}]
set_max_capacitance 0.15 [get_ports {in_data[46]}]
set_max_capacitance 0.15 [get_ports {in_data[45]}]
set_max_capacitance 0.15 [get_ports {in_data[44]}]
set_max_capacitance 0.15 [get_ports {in_data[43]}]
set_max_capacitance 0.15 [get_ports {in_data[42]}]
set_max_capacitance 0.15 [get_ports {in_data[41]}]
set_max_capacitance 0.15 [get_ports {in_data[40]}]
set_max_capacitance 0.15 [get_ports {in_data[39]}]
set_max_capacitance 0.15 [get_ports {in_data[38]}]
set_max_capacitance 0.15 [get_ports {in_data[37]}]
set_max_capacitance 0.15 [get_ports {in_data[36]}]
set_max_capacitance 0.15 [get_ports {in_data[35]}]
set_max_capacitance 0.15 [get_ports {in_data[34]}]
set_max_capacitance 0.15 [get_ports {in_data[33]}]
set_max_capacitance 0.15 [get_ports {in_data[32]}]
set_max_capacitance 0.15 [get_ports {in_data[31]}]
set_max_capacitance 0.15 [get_ports {in_data[30]}]
set_max_capacitance 0.15 [get_ports {in_data[29]}]
set_max_capacitance 0.15 [get_ports {in_data[28]}]
set_max_capacitance 0.15 [get_ports {in_data[27]}]
set_max_capacitance 0.15 [get_ports {in_data[26]}]
set_max_capacitance 0.15 [get_ports {in_data[25]}]
set_max_capacitance 0.15 [get_ports {in_data[24]}]
set_max_capacitance 0.15 [get_ports {in_data[23]}]
set_max_capacitance 0.15 [get_ports {in_data[22]}]
set_max_capacitance 0.15 [get_ports {in_data[21]}]
set_max_capacitance 0.15 [get_ports {in_data[20]}]
set_max_capacitance 0.15 [get_ports {in_data[19]}]
set_max_capacitance 0.15 [get_ports {in_data[18]}]
set_max_capacitance 0.15 [get_ports {in_data[17]}]
set_max_capacitance 0.15 [get_ports {in_data[16]}]
set_max_capacitance 0.15 [get_ports {in_data[15]}]
set_max_capacitance 0.15 [get_ports {in_data[14]}]
set_max_capacitance 0.15 [get_ports {in_data[13]}]
set_max_capacitance 0.15 [get_ports {in_data[12]}]
set_max_capacitance 0.15 [get_ports {in_data[11]}]
set_max_capacitance 0.15 [get_ports {in_data[10]}]
set_max_capacitance 0.15 [get_ports {in_data[9]}]
set_max_capacitance 0.15 [get_ports {in_data[8]}]
set_max_capacitance 0.15 [get_ports {in_data[7]}]
set_max_capacitance 0.15 [get_ports {in_data[6]}]
set_max_capacitance 0.15 [get_ports {in_data[5]}]
set_max_capacitance 0.15 [get_ports {in_data[4]}]
set_max_capacitance 0.15 [get_ports {in_data[3]}]
set_max_capacitance 0.15 [get_ports {in_data[2]}]
set_max_capacitance 0.15 [get_ports {in_data[1]}]
set_max_capacitance 0.15 [get_ports {in_data[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports {in_data[71]}]
set_max_fanout 10 [get_ports {in_data[70]}]
set_max_fanout 10 [get_ports {in_data[69]}]
set_max_fanout 10 [get_ports {in_data[68]}]
set_max_fanout 10 [get_ports {in_data[67]}]
set_max_fanout 10 [get_ports {in_data[66]}]
set_max_fanout 10 [get_ports {in_data[65]}]
set_max_fanout 10 [get_ports {in_data[64]}]
set_max_fanout 10 [get_ports {in_data[63]}]
set_max_fanout 10 [get_ports {in_data[62]}]
set_max_fanout 10 [get_ports {in_data[61]}]
set_max_fanout 10 [get_ports {in_data[60]}]
set_max_fanout 10 [get_ports {in_data[59]}]
set_max_fanout 10 [get_ports {in_data[58]}]
set_max_fanout 10 [get_ports {in_data[57]}]
set_max_fanout 10 [get_ports {in_data[56]}]
set_max_fanout 10 [get_ports {in_data[55]}]
set_max_fanout 10 [get_ports {in_data[54]}]
set_max_fanout 10 [get_ports {in_data[53]}]
set_max_fanout 10 [get_ports {in_data[52]}]
set_max_fanout 10 [get_ports {in_data[51]}]
set_max_fanout 10 [get_ports {in_data[50]}]
set_max_fanout 10 [get_ports {in_data[49]}]
set_max_fanout 10 [get_ports {in_data[48]}]
set_max_fanout 10 [get_ports {in_data[47]}]
set_max_fanout 10 [get_ports {in_data[46]}]
set_max_fanout 10 [get_ports {in_data[45]}]
set_max_fanout 10 [get_ports {in_data[44]}]
set_max_fanout 10 [get_ports {in_data[43]}]
set_max_fanout 10 [get_ports {in_data[42]}]
set_max_fanout 10 [get_ports {in_data[41]}]
set_max_fanout 10 [get_ports {in_data[40]}]
set_max_fanout 10 [get_ports {in_data[39]}]
set_max_fanout 10 [get_ports {in_data[38]}]
set_max_fanout 10 [get_ports {in_data[37]}]
set_max_fanout 10 [get_ports {in_data[36]}]
set_max_fanout 10 [get_ports {in_data[35]}]
set_max_fanout 10 [get_ports {in_data[34]}]
set_max_fanout 10 [get_ports {in_data[33]}]
set_max_fanout 10 [get_ports {in_data[32]}]
set_max_fanout 10 [get_ports {in_data[31]}]
set_max_fanout 10 [get_ports {in_data[30]}]
set_max_fanout 10 [get_ports {in_data[29]}]
set_max_fanout 10 [get_ports {in_data[28]}]
set_max_fanout 10 [get_ports {in_data[27]}]
set_max_fanout 10 [get_ports {in_data[26]}]
set_max_fanout 10 [get_ports {in_data[25]}]
set_max_fanout 10 [get_ports {in_data[24]}]
set_max_fanout 10 [get_ports {in_data[23]}]
set_max_fanout 10 [get_ports {in_data[22]}]
set_max_fanout 10 [get_ports {in_data[21]}]
set_max_fanout 10 [get_ports {in_data[20]}]
set_max_fanout 10 [get_ports {in_data[19]}]
set_max_fanout 10 [get_ports {in_data[18]}]
set_max_fanout 10 [get_ports {in_data[17]}]
set_max_fanout 10 [get_ports {in_data[16]}]
set_max_fanout 10 [get_ports {in_data[15]}]
set_max_fanout 10 [get_ports {in_data[14]}]
set_max_fanout 10 [get_ports {in_data[13]}]
set_max_fanout 10 [get_ports {in_data[12]}]
set_max_fanout 10 [get_ports {in_data[11]}]
set_max_fanout 10 [get_ports {in_data[10]}]
set_max_fanout 10 [get_ports {in_data[9]}]
set_max_fanout 10 [get_ports {in_data[8]}]
set_max_fanout 10 [get_ports {in_data[7]}]
set_max_fanout 10 [get_ports {in_data[6]}]
set_max_fanout 10 [get_ports {in_data[5]}]
set_max_fanout 10 [get_ports {in_data[4]}]
set_max_fanout 10 [get_ports {in_data[3]}]
set_max_fanout 10 [get_ports {in_data[2]}]
set_max_fanout 10 [get_ports {in_data[1]}]
set_max_fanout 10 [get_ports {in_data[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports {in_data[71]}]
set_max_transition 3 [get_ports {in_data[70]}]
set_max_transition 3 [get_ports {in_data[69]}]
set_max_transition 3 [get_ports {in_data[68]}]
set_max_transition 3 [get_ports {in_data[67]}]
set_max_transition 3 [get_ports {in_data[66]}]
set_max_transition 3 [get_ports {in_data[65]}]
set_max_transition 3 [get_ports {in_data[64]}]
set_max_transition 3 [get_ports {in_data[63]}]
set_max_transition 3 [get_ports {in_data[62]}]
set_max_transition 3 [get_ports {in_data[61]}]
set_max_transition 3 [get_ports {in_data[60]}]
set_max_transition 3 [get_ports {in_data[59]}]
set_max_transition 3 [get_ports {in_data[58]}]
set_max_transition 3 [get_ports {in_data[57]}]
set_max_transition 3 [get_ports {in_data[56]}]
set_max_transition 3 [get_ports {in_data[55]}]
set_max_transition 3 [get_ports {in_data[54]}]
set_max_transition 3 [get_ports {in_data[53]}]
set_max_transition 3 [get_ports {in_data[52]}]
set_max_transition 3 [get_ports {in_data[51]}]
set_max_transition 3 [get_ports {in_data[50]}]
set_max_transition 3 [get_ports {in_data[49]}]
set_max_transition 3 [get_ports {in_data[48]}]
set_max_transition 3 [get_ports {in_data[47]}]
set_max_transition 3 [get_ports {in_data[46]}]
set_max_transition 3 [get_ports {in_data[45]}]
set_max_transition 3 [get_ports {in_data[44]}]
set_max_transition 3 [get_ports {in_data[43]}]
set_max_transition 3 [get_ports {in_data[42]}]
set_max_transition 3 [get_ports {in_data[41]}]
set_max_transition 3 [get_ports {in_data[40]}]
set_max_transition 3 [get_ports {in_data[39]}]
set_max_transition 3 [get_ports {in_data[38]}]
set_max_transition 3 [get_ports {in_data[37]}]
set_max_transition 3 [get_ports {in_data[36]}]
set_max_transition 3 [get_ports {in_data[35]}]
set_max_transition 3 [get_ports {in_data[34]}]
set_max_transition 3 [get_ports {in_data[33]}]
set_max_transition 3 [get_ports {in_data[32]}]
set_max_transition 3 [get_ports {in_data[31]}]
set_max_transition 3 [get_ports {in_data[30]}]
set_max_transition 3 [get_ports {in_data[29]}]
set_max_transition 3 [get_ports {in_data[28]}]
set_max_transition 3 [get_ports {in_data[27]}]
set_max_transition 3 [get_ports {in_data[26]}]
set_max_transition 3 [get_ports {in_data[25]}]
set_max_transition 3 [get_ports {in_data[24]}]
set_max_transition 3 [get_ports {in_data[23]}]
set_max_transition 3 [get_ports {in_data[22]}]
set_max_transition 3 [get_ports {in_data[21]}]
set_max_transition 3 [get_ports {in_data[20]}]
set_max_transition 3 [get_ports {in_data[19]}]
set_max_transition 3 [get_ports {in_data[18]}]
set_max_transition 3 [get_ports {in_data[17]}]
set_max_transition 3 [get_ports {in_data[16]}]
set_max_transition 3 [get_ports {in_data[15]}]
set_max_transition 3 [get_ports {in_data[14]}]
set_max_transition 3 [get_ports {in_data[13]}]
set_max_transition 3 [get_ports {in_data[12]}]
set_max_transition 3 [get_ports {in_data[11]}]
set_max_transition 3 [get_ports {in_data[10]}]
set_max_transition 3 [get_ports {in_data[9]}]
set_max_transition 3 [get_ports {in_data[8]}]
set_max_transition 3 [get_ports {in_data[7]}]
set_max_transition 3 [get_ports {in_data[6]}]
set_max_transition 3 [get_ports {in_data[5]}]
set_max_transition 3 [get_ports {in_data[4]}]
set_max_transition 3 [get_ports {in_data[3]}]
set_max_transition 3 [get_ports {in_data[2]}]
set_max_transition 3 [get_ports {in_data[1]}]
set_max_transition 3 [get_ports {in_data[0]}]
create_clock [get_ports clk]  -period 9.8  -waveform {0 4.9}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 4.9  [get_ports in_valid]
set_input_delay -clock clk  -min 0  [get_ports in_valid]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[71]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[71]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[70]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[70]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[69]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[69]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[68]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[68]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[67]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[67]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[66]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[66]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[65]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[65]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[64]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[64]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[63]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[63]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[62]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[62]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[61]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[61]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[60]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[60]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[59]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[59]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[58]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[58]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[57]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[57]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[56]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[56]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[55]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[55]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[54]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[54]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[53]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[53]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[52]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[52]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[51]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[51]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[50]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[50]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[49]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[49]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[48]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[48]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[47]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[47]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[46]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[46]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[45]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[45]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[44]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[44]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[43]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[43]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[42]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[42]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[41]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[41]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[40]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[40]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[39]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[39]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[38]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[38]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[37]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[37]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[36]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[36]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[35]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[35]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[34]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[34]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[33]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[33]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[32]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[32]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[31]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[31]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[30]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[30]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[29]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[29]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[28]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[28]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[27]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[27]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[26]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[26]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[25]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[25]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[24]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[24]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[23]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[23]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[22]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[22]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[21]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[21]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[20]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[20]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[19]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[19]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[18]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[18]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[17]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[17]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[16]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[16]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[15]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[15]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[14]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[14]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[13]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[13]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[12]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[12]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[11]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[11]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[10]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[10]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[9]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[9]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[8]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[8]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[7]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[7]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[6]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[6]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[5]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[5]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[4]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[4]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[3]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[3]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[2]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[1]}]
set_input_delay -clock clk  -max 4.9  [get_ports {in_data[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[0]}]
set_output_delay -clock clk  -max 4.9  [get_ports out_valid]
set_output_delay -clock clk  -min 0  [get_ports out_valid]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[215]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[215]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[214]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[214]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[213]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[213]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[212]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[212]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[211]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[211]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[210]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[210]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[209]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[209]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[208]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[208]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[207]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[207]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[206]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[206]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[205]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[205]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[204]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[204]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[203]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[203]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[202]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[202]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[201]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[201]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[200]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[200]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[199]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[199]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[198]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[198]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[197]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[197]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[196]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[196]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[195]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[195]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[194]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[194]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[193]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[193]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[192]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[192]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[191]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[191]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[190]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[190]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[189]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[189]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[188]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[188]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[187]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[187]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[186]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[186]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[185]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[185]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[184]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[184]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[183]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[183]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[182]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[182]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[181]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[181]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[180]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[180]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[179]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[179]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[178]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[178]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[177]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[177]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[176]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[176]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[175]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[175]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[174]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[174]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[173]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[173]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[172]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[172]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[171]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[171]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[170]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[170]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[169]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[169]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[168]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[168]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[167]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[167]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[166]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[166]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[165]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[165]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[164]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[164]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[163]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[163]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[162]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[162]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[161]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[161]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[160]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[160]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[159]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[159]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[158]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[158]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[157]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[157]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[156]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[156]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[155]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[155]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[154]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[154]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[153]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[153]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[152]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[152]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[151]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[151]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[150]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[150]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[149]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[149]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[148]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[148]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[147]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[147]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[146]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[146]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[145]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[145]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[144]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[144]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[143]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[143]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[142]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[142]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[141]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[141]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[140]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[140]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[139]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[139]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[138]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[138]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[137]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[137]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[136]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[136]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[135]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[135]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[134]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[134]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[133]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[133]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[132]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[132]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[131]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[131]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[130]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[130]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[129]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[129]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[128]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[128]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[127]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[127]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[126]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[126]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[125]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[125]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[124]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[124]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[123]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[123]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[122]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[122]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[121]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[121]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[120]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[120]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[119]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[119]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[118]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[118]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[117]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[117]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[116]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[116]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[115]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[115]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[114]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[114]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[113]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[113]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[112]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[112]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[111]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[111]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[110]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[110]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[109]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[109]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[108]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[108]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[107]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[107]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[106]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[106]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[105]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[105]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[104]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[104]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[103]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[103]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[102]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[102]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[101]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[101]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[100]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[100]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[99]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[99]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[98]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[98]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[97]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[97]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[96]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[96]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[95]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[95]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[94]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[94]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[93]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[93]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[92]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[92]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[91]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[91]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[90]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[90]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[89]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[89]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[88]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[88]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[87]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[87]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[86]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[86]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[85]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[85]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[84]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[84]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[83]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[83]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[82]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[82]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[81]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[81]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[80]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[80]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[79]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[79]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[78]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[78]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[77]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[77]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[76]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[76]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[75]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[75]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[74]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[74]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[73]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[73]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[72]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[72]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[71]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[71]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[70]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[70]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[69]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[69]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[68]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[68]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[67]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[67]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[66]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[66]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[65]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[65]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[64]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[64]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[63]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[63]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[62]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[62]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[61]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[61]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[60]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[60]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[59]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[59]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[58]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[58]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[57]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[57]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[56]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[56]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[55]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[55]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[54]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[54]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[53]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[53]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[52]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[52]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[51]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[51]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[50]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[50]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[49]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[49]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[48]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[48]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[47]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[47]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[46]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[46]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[45]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[45]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[44]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[44]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[43]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[43]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[42]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[42]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[41]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[41]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[40]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[40]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[39]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[39]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[38]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[38]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[37]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[37]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[36]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[36]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[35]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[35]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[34]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[34]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[33]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[33]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[32]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[32]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[31]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[31]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[30]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[30]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[29]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[29]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[28]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[28]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[27]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[27]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[26]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[26]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[25]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[25]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[24]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[24]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[23]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[23]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[22]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[22]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[21]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[21]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[20]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[20]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[19]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[19]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[18]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[18]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[17]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[17]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[16]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[16]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[15]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[15]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[14]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[14]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[13]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[13]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[12]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[12]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[11]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[11]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[10]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[10]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[9]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[9]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[8]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[8]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[7]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[7]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[6]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[6]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[5]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[5]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[4]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[4]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[3]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[3]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[2]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[2]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[1]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[1]}]
set_output_delay -clock clk  -max 4.9  [get_ports {out_data[0]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {in_data[71]}]
set_input_transition -min 0.5  [get_ports {in_data[71]}]
set_input_transition -max 0.5  [get_ports {in_data[70]}]
set_input_transition -min 0.5  [get_ports {in_data[70]}]
set_input_transition -max 0.5  [get_ports {in_data[69]}]
set_input_transition -min 0.5  [get_ports {in_data[69]}]
set_input_transition -max 0.5  [get_ports {in_data[68]}]
set_input_transition -min 0.5  [get_ports {in_data[68]}]
set_input_transition -max 0.5  [get_ports {in_data[67]}]
set_input_transition -min 0.5  [get_ports {in_data[67]}]
set_input_transition -max 0.5  [get_ports {in_data[66]}]
set_input_transition -min 0.5  [get_ports {in_data[66]}]
set_input_transition -max 0.5  [get_ports {in_data[65]}]
set_input_transition -min 0.5  [get_ports {in_data[65]}]
set_input_transition -max 0.5  [get_ports {in_data[64]}]
set_input_transition -min 0.5  [get_ports {in_data[64]}]
set_input_transition -max 0.5  [get_ports {in_data[63]}]
set_input_transition -min 0.5  [get_ports {in_data[63]}]
set_input_transition -max 0.5  [get_ports {in_data[62]}]
set_input_transition -min 0.5  [get_ports {in_data[62]}]
set_input_transition -max 0.5  [get_ports {in_data[61]}]
set_input_transition -min 0.5  [get_ports {in_data[61]}]
set_input_transition -max 0.5  [get_ports {in_data[60]}]
set_input_transition -min 0.5  [get_ports {in_data[60]}]
set_input_transition -max 0.5  [get_ports {in_data[59]}]
set_input_transition -min 0.5  [get_ports {in_data[59]}]
set_input_transition -max 0.5  [get_ports {in_data[58]}]
set_input_transition -min 0.5  [get_ports {in_data[58]}]
set_input_transition -max 0.5  [get_ports {in_data[57]}]
set_input_transition -min 0.5  [get_ports {in_data[57]}]
set_input_transition -max 0.5  [get_ports {in_data[56]}]
set_input_transition -min 0.5  [get_ports {in_data[56]}]
set_input_transition -max 0.5  [get_ports {in_data[55]}]
set_input_transition -min 0.5  [get_ports {in_data[55]}]
set_input_transition -max 0.5  [get_ports {in_data[54]}]
set_input_transition -min 0.5  [get_ports {in_data[54]}]
set_input_transition -max 0.5  [get_ports {in_data[53]}]
set_input_transition -min 0.5  [get_ports {in_data[53]}]
set_input_transition -max 0.5  [get_ports {in_data[52]}]
set_input_transition -min 0.5  [get_ports {in_data[52]}]
set_input_transition -max 0.5  [get_ports {in_data[51]}]
set_input_transition -min 0.5  [get_ports {in_data[51]}]
set_input_transition -max 0.5  [get_ports {in_data[50]}]
set_input_transition -min 0.5  [get_ports {in_data[50]}]
set_input_transition -max 0.5  [get_ports {in_data[49]}]
set_input_transition -min 0.5  [get_ports {in_data[49]}]
set_input_transition -max 0.5  [get_ports {in_data[48]}]
set_input_transition -min 0.5  [get_ports {in_data[48]}]
set_input_transition -max 0.5  [get_ports {in_data[47]}]
set_input_transition -min 0.5  [get_ports {in_data[47]}]
set_input_transition -max 0.5  [get_ports {in_data[46]}]
set_input_transition -min 0.5  [get_ports {in_data[46]}]
set_input_transition -max 0.5  [get_ports {in_data[45]}]
set_input_transition -min 0.5  [get_ports {in_data[45]}]
set_input_transition -max 0.5  [get_ports {in_data[44]}]
set_input_transition -min 0.5  [get_ports {in_data[44]}]
set_input_transition -max 0.5  [get_ports {in_data[43]}]
set_input_transition -min 0.5  [get_ports {in_data[43]}]
set_input_transition -max 0.5  [get_ports {in_data[42]}]
set_input_transition -min 0.5  [get_ports {in_data[42]}]
set_input_transition -max 0.5  [get_ports {in_data[41]}]
set_input_transition -min 0.5  [get_ports {in_data[41]}]
set_input_transition -max 0.5  [get_ports {in_data[40]}]
set_input_transition -min 0.5  [get_ports {in_data[40]}]
set_input_transition -max 0.5  [get_ports {in_data[39]}]
set_input_transition -min 0.5  [get_ports {in_data[39]}]
set_input_transition -max 0.5  [get_ports {in_data[38]}]
set_input_transition -min 0.5  [get_ports {in_data[38]}]
set_input_transition -max 0.5  [get_ports {in_data[37]}]
set_input_transition -min 0.5  [get_ports {in_data[37]}]
set_input_transition -max 0.5  [get_ports {in_data[36]}]
set_input_transition -min 0.5  [get_ports {in_data[36]}]
set_input_transition -max 0.5  [get_ports {in_data[35]}]
set_input_transition -min 0.5  [get_ports {in_data[35]}]
set_input_transition -max 0.5  [get_ports {in_data[34]}]
set_input_transition -min 0.5  [get_ports {in_data[34]}]
set_input_transition -max 0.5  [get_ports {in_data[33]}]
set_input_transition -min 0.5  [get_ports {in_data[33]}]
set_input_transition -max 0.5  [get_ports {in_data[32]}]
set_input_transition -min 0.5  [get_ports {in_data[32]}]
set_input_transition -max 0.5  [get_ports {in_data[31]}]
set_input_transition -min 0.5  [get_ports {in_data[31]}]
set_input_transition -max 0.5  [get_ports {in_data[30]}]
set_input_transition -min 0.5  [get_ports {in_data[30]}]
set_input_transition -max 0.5  [get_ports {in_data[29]}]
set_input_transition -min 0.5  [get_ports {in_data[29]}]
set_input_transition -max 0.5  [get_ports {in_data[28]}]
set_input_transition -min 0.5  [get_ports {in_data[28]}]
set_input_transition -max 0.5  [get_ports {in_data[27]}]
set_input_transition -min 0.5  [get_ports {in_data[27]}]
set_input_transition -max 0.5  [get_ports {in_data[26]}]
set_input_transition -min 0.5  [get_ports {in_data[26]}]
set_input_transition -max 0.5  [get_ports {in_data[25]}]
set_input_transition -min 0.5  [get_ports {in_data[25]}]
set_input_transition -max 0.5  [get_ports {in_data[24]}]
set_input_transition -min 0.5  [get_ports {in_data[24]}]
set_input_transition -max 0.5  [get_ports {in_data[23]}]
set_input_transition -min 0.5  [get_ports {in_data[23]}]
set_input_transition -max 0.5  [get_ports {in_data[22]}]
set_input_transition -min 0.5  [get_ports {in_data[22]}]
set_input_transition -max 0.5  [get_ports {in_data[21]}]
set_input_transition -min 0.5  [get_ports {in_data[21]}]
set_input_transition -max 0.5  [get_ports {in_data[20]}]
set_input_transition -min 0.5  [get_ports {in_data[20]}]
set_input_transition -max 0.5  [get_ports {in_data[19]}]
set_input_transition -min 0.5  [get_ports {in_data[19]}]
set_input_transition -max 0.5  [get_ports {in_data[18]}]
set_input_transition -min 0.5  [get_ports {in_data[18]}]
set_input_transition -max 0.5  [get_ports {in_data[17]}]
set_input_transition -min 0.5  [get_ports {in_data[17]}]
set_input_transition -max 0.5  [get_ports {in_data[16]}]
set_input_transition -min 0.5  [get_ports {in_data[16]}]
set_input_transition -max 0.5  [get_ports {in_data[15]}]
set_input_transition -min 0.5  [get_ports {in_data[15]}]
set_input_transition -max 0.5  [get_ports {in_data[14]}]
set_input_transition -min 0.5  [get_ports {in_data[14]}]
set_input_transition -max 0.5  [get_ports {in_data[13]}]
set_input_transition -min 0.5  [get_ports {in_data[13]}]
set_input_transition -max 0.5  [get_ports {in_data[12]}]
set_input_transition -min 0.5  [get_ports {in_data[12]}]
set_input_transition -max 0.5  [get_ports {in_data[11]}]
set_input_transition -min 0.5  [get_ports {in_data[11]}]
set_input_transition -max 0.5  [get_ports {in_data[10]}]
set_input_transition -min 0.5  [get_ports {in_data[10]}]
set_input_transition -max 0.5  [get_ports {in_data[9]}]
set_input_transition -min 0.5  [get_ports {in_data[9]}]
set_input_transition -max 0.5  [get_ports {in_data[8]}]
set_input_transition -min 0.5  [get_ports {in_data[8]}]
set_input_transition -max 0.5  [get_ports {in_data[7]}]
set_input_transition -min 0.5  [get_ports {in_data[7]}]
set_input_transition -max 0.5  [get_ports {in_data[6]}]
set_input_transition -min 0.5  [get_ports {in_data[6]}]
set_input_transition -max 0.5  [get_ports {in_data[5]}]
set_input_transition -min 0.5  [get_ports {in_data[5]}]
set_input_transition -max 0.5  [get_ports {in_data[4]}]
set_input_transition -min 0.5  [get_ports {in_data[4]}]
set_input_transition -max 0.5  [get_ports {in_data[3]}]
set_input_transition -min 0.5  [get_ports {in_data[3]}]
set_input_transition -max 0.5  [get_ports {in_data[2]}]
set_input_transition -min 0.5  [get_ports {in_data[2]}]
set_input_transition -max 0.5  [get_ports {in_data[1]}]
set_input_transition -min 0.5  [get_ports {in_data[1]}]
set_input_transition -max 0.5  [get_ports {in_data[0]}]
set_input_transition -min 0.5  [get_ports {in_data[0]}]
