###################################################################

# Created by write_sdc on Thu Apr  9 04:01:51 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {out_data[19]}]
set_load -pin_load 0.05 [get_ports {out_data[18]}]
set_load -pin_load 0.05 [get_ports {out_data[17]}]
set_load -pin_load 0.05 [get_ports {out_data[16]}]
set_load -pin_load 0.05 [get_ports {out_data[15]}]
set_load -pin_load 0.05 [get_ports {out_data[14]}]
set_load -pin_load 0.05 [get_ports {out_data[13]}]
set_load -pin_load 0.05 [get_ports {out_data[12]}]
set_load -pin_load 0.05 [get_ports {out_data[11]}]
set_load -pin_load 0.05 [get_ports {out_data[10]}]
set_load -pin_load 0.05 [get_ports {out_data[9]}]
set_load -pin_load 0.05 [get_ports {out_data[8]}]
set_load -pin_load 0.05 [get_ports {out_data[7]}]
set_load -pin_load 0.05 [get_ports {out_data[6]}]
set_load -pin_load 0.05 [get_ports {out_data[5]}]
set_load -pin_load 0.05 [get_ports {out_data[4]}]
set_load -pin_load 0.05 [get_ports {out_data[3]}]
set_load -pin_load 0.05 [get_ports {out_data[2]}]
set_load -pin_load 0.05 [get_ports {out_data[1]}]
set_load -pin_load 0.05 [get_ports {out_data[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports {in_data[63]}]
set_max_capacitance 0.15 [get_ports {in_data[62]}]
set_max_capacitance 0.15 [get_ports {in_data[61]}]
set_max_capacitance 0.15 [get_ports {in_data[60]}]
set_max_capacitance 0.15 [get_ports {in_data[59]}]
set_max_capacitance 0.15 [get_ports {in_data[58]}]
set_max_capacitance 0.15 [get_ports {in_data[57]}]
set_max_capacitance 0.15 [get_ports {in_data[56]}]
set_max_capacitance 0.15 [get_ports {in_data[55]}]
set_max_capacitance 0.15 [get_ports {in_data[54]}]
set_max_capacitance 0.15 [get_ports {in_data[53]}]
set_max_capacitance 0.15 [get_ports {in_data[52]}]
set_max_capacitance 0.15 [get_ports {in_data[51]}]
set_max_capacitance 0.15 [get_ports {in_data[50]}]
set_max_capacitance 0.15 [get_ports {in_data[49]}]
set_max_capacitance 0.15 [get_ports {in_data[48]}]
set_max_capacitance 0.15 [get_ports {in_data[47]}]
set_max_capacitance 0.15 [get_ports {in_data[46]}]
set_max_capacitance 0.15 [get_ports {in_data[45]}]
set_max_capacitance 0.15 [get_ports {in_data[44]}]
set_max_capacitance 0.15 [get_ports {in_data[43]}]
set_max_capacitance 0.15 [get_ports {in_data[42]}]
set_max_capacitance 0.15 [get_ports {in_data[41]}]
set_max_capacitance 0.15 [get_ports {in_data[40]}]
set_max_capacitance 0.15 [get_ports {in_data[39]}]
set_max_capacitance 0.15 [get_ports {in_data[38]}]
set_max_capacitance 0.15 [get_ports {in_data[37]}]
set_max_capacitance 0.15 [get_ports {in_data[36]}]
set_max_capacitance 0.15 [get_ports {in_data[35]}]
set_max_capacitance 0.15 [get_ports {in_data[34]}]
set_max_capacitance 0.15 [get_ports {in_data[33]}]
set_max_capacitance 0.15 [get_ports {in_data[32]}]
set_max_capacitance 0.15 [get_ports {in_data[31]}]
set_max_capacitance 0.15 [get_ports {in_data[30]}]
set_max_capacitance 0.15 [get_ports {in_data[29]}]
set_max_capacitance 0.15 [get_ports {in_data[28]}]
set_max_capacitance 0.15 [get_ports {in_data[27]}]
set_max_capacitance 0.15 [get_ports {in_data[26]}]
set_max_capacitance 0.15 [get_ports {in_data[25]}]
set_max_capacitance 0.15 [get_ports {in_data[24]}]
set_max_capacitance 0.15 [get_ports {in_data[23]}]
set_max_capacitance 0.15 [get_ports {in_data[22]}]
set_max_capacitance 0.15 [get_ports {in_data[21]}]
set_max_capacitance 0.15 [get_ports {in_data[20]}]
set_max_capacitance 0.15 [get_ports {in_data[19]}]
set_max_capacitance 0.15 [get_ports {in_data[18]}]
set_max_capacitance 0.15 [get_ports {in_data[17]}]
set_max_capacitance 0.15 [get_ports {in_data[16]}]
set_max_capacitance 0.15 [get_ports {in_data[15]}]
set_max_capacitance 0.15 [get_ports {in_data[14]}]
set_max_capacitance 0.15 [get_ports {in_data[13]}]
set_max_capacitance 0.15 [get_ports {in_data[12]}]
set_max_capacitance 0.15 [get_ports {in_data[11]}]
set_max_capacitance 0.15 [get_ports {in_data[10]}]
set_max_capacitance 0.15 [get_ports {in_data[9]}]
set_max_capacitance 0.15 [get_ports {in_data[8]}]
set_max_capacitance 0.15 [get_ports {in_data[7]}]
set_max_capacitance 0.15 [get_ports {in_data[6]}]
set_max_capacitance 0.15 [get_ports {in_data[5]}]
set_max_capacitance 0.15 [get_ports {in_data[4]}]
set_max_capacitance 0.15 [get_ports {in_data[3]}]
set_max_capacitance 0.15 [get_ports {in_data[2]}]
set_max_capacitance 0.15 [get_ports {in_data[1]}]
set_max_capacitance 0.15 [get_ports {in_data[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports {in_data[63]}]
set_max_fanout 10 [get_ports {in_data[62]}]
set_max_fanout 10 [get_ports {in_data[61]}]
set_max_fanout 10 [get_ports {in_data[60]}]
set_max_fanout 10 [get_ports {in_data[59]}]
set_max_fanout 10 [get_ports {in_data[58]}]
set_max_fanout 10 [get_ports {in_data[57]}]
set_max_fanout 10 [get_ports {in_data[56]}]
set_max_fanout 10 [get_ports {in_data[55]}]
set_max_fanout 10 [get_ports {in_data[54]}]
set_max_fanout 10 [get_ports {in_data[53]}]
set_max_fanout 10 [get_ports {in_data[52]}]
set_max_fanout 10 [get_ports {in_data[51]}]
set_max_fanout 10 [get_ports {in_data[50]}]
set_max_fanout 10 [get_ports {in_data[49]}]
set_max_fanout 10 [get_ports {in_data[48]}]
set_max_fanout 10 [get_ports {in_data[47]}]
set_max_fanout 10 [get_ports {in_data[46]}]
set_max_fanout 10 [get_ports {in_data[45]}]
set_max_fanout 10 [get_ports {in_data[44]}]
set_max_fanout 10 [get_ports {in_data[43]}]
set_max_fanout 10 [get_ports {in_data[42]}]
set_max_fanout 10 [get_ports {in_data[41]}]
set_max_fanout 10 [get_ports {in_data[40]}]
set_max_fanout 10 [get_ports {in_data[39]}]
set_max_fanout 10 [get_ports {in_data[38]}]
set_max_fanout 10 [get_ports {in_data[37]}]
set_max_fanout 10 [get_ports {in_data[36]}]
set_max_fanout 10 [get_ports {in_data[35]}]
set_max_fanout 10 [get_ports {in_data[34]}]
set_max_fanout 10 [get_ports {in_data[33]}]
set_max_fanout 10 [get_ports {in_data[32]}]
set_max_fanout 10 [get_ports {in_data[31]}]
set_max_fanout 10 [get_ports {in_data[30]}]
set_max_fanout 10 [get_ports {in_data[29]}]
set_max_fanout 10 [get_ports {in_data[28]}]
set_max_fanout 10 [get_ports {in_data[27]}]
set_max_fanout 10 [get_ports {in_data[26]}]
set_max_fanout 10 [get_ports {in_data[25]}]
set_max_fanout 10 [get_ports {in_data[24]}]
set_max_fanout 10 [get_ports {in_data[23]}]
set_max_fanout 10 [get_ports {in_data[22]}]
set_max_fanout 10 [get_ports {in_data[21]}]
set_max_fanout 10 [get_ports {in_data[20]}]
set_max_fanout 10 [get_ports {in_data[19]}]
set_max_fanout 10 [get_ports {in_data[18]}]
set_max_fanout 10 [get_ports {in_data[17]}]
set_max_fanout 10 [get_ports {in_data[16]}]
set_max_fanout 10 [get_ports {in_data[15]}]
set_max_fanout 10 [get_ports {in_data[14]}]
set_max_fanout 10 [get_ports {in_data[13]}]
set_max_fanout 10 [get_ports {in_data[12]}]
set_max_fanout 10 [get_ports {in_data[11]}]
set_max_fanout 10 [get_ports {in_data[10]}]
set_max_fanout 10 [get_ports {in_data[9]}]
set_max_fanout 10 [get_ports {in_data[8]}]
set_max_fanout 10 [get_ports {in_data[7]}]
set_max_fanout 10 [get_ports {in_data[6]}]
set_max_fanout 10 [get_ports {in_data[5]}]
set_max_fanout 10 [get_ports {in_data[4]}]
set_max_fanout 10 [get_ports {in_data[3]}]
set_max_fanout 10 [get_ports {in_data[2]}]
set_max_fanout 10 [get_ports {in_data[1]}]
set_max_fanout 10 [get_ports {in_data[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports {in_data[63]}]
set_max_transition 3 [get_ports {in_data[62]}]
set_max_transition 3 [get_ports {in_data[61]}]
set_max_transition 3 [get_ports {in_data[60]}]
set_max_transition 3 [get_ports {in_data[59]}]
set_max_transition 3 [get_ports {in_data[58]}]
set_max_transition 3 [get_ports {in_data[57]}]
set_max_transition 3 [get_ports {in_data[56]}]
set_max_transition 3 [get_ports {in_data[55]}]
set_max_transition 3 [get_ports {in_data[54]}]
set_max_transition 3 [get_ports {in_data[53]}]
set_max_transition 3 [get_ports {in_data[52]}]
set_max_transition 3 [get_ports {in_data[51]}]
set_max_transition 3 [get_ports {in_data[50]}]
set_max_transition 3 [get_ports {in_data[49]}]
set_max_transition 3 [get_ports {in_data[48]}]
set_max_transition 3 [get_ports {in_data[47]}]
set_max_transition 3 [get_ports {in_data[46]}]
set_max_transition 3 [get_ports {in_data[45]}]
set_max_transition 3 [get_ports {in_data[44]}]
set_max_transition 3 [get_ports {in_data[43]}]
set_max_transition 3 [get_ports {in_data[42]}]
set_max_transition 3 [get_ports {in_data[41]}]
set_max_transition 3 [get_ports {in_data[40]}]
set_max_transition 3 [get_ports {in_data[39]}]
set_max_transition 3 [get_ports {in_data[38]}]
set_max_transition 3 [get_ports {in_data[37]}]
set_max_transition 3 [get_ports {in_data[36]}]
set_max_transition 3 [get_ports {in_data[35]}]
set_max_transition 3 [get_ports {in_data[34]}]
set_max_transition 3 [get_ports {in_data[33]}]
set_max_transition 3 [get_ports {in_data[32]}]
set_max_transition 3 [get_ports {in_data[31]}]
set_max_transition 3 [get_ports {in_data[30]}]
set_max_transition 3 [get_ports {in_data[29]}]
set_max_transition 3 [get_ports {in_data[28]}]
set_max_transition 3 [get_ports {in_data[27]}]
set_max_transition 3 [get_ports {in_data[26]}]
set_max_transition 3 [get_ports {in_data[25]}]
set_max_transition 3 [get_ports {in_data[24]}]
set_max_transition 3 [get_ports {in_data[23]}]
set_max_transition 3 [get_ports {in_data[22]}]
set_max_transition 3 [get_ports {in_data[21]}]
set_max_transition 3 [get_ports {in_data[20]}]
set_max_transition 3 [get_ports {in_data[19]}]
set_max_transition 3 [get_ports {in_data[18]}]
set_max_transition 3 [get_ports {in_data[17]}]
set_max_transition 3 [get_ports {in_data[16]}]
set_max_transition 3 [get_ports {in_data[15]}]
set_max_transition 3 [get_ports {in_data[14]}]
set_max_transition 3 [get_ports {in_data[13]}]
set_max_transition 3 [get_ports {in_data[12]}]
set_max_transition 3 [get_ports {in_data[11]}]
set_max_transition 3 [get_ports {in_data[10]}]
set_max_transition 3 [get_ports {in_data[9]}]
set_max_transition 3 [get_ports {in_data[8]}]
set_max_transition 3 [get_ports {in_data[7]}]
set_max_transition 3 [get_ports {in_data[6]}]
set_max_transition 3 [get_ports {in_data[5]}]
set_max_transition 3 [get_ports {in_data[4]}]
set_max_transition 3 [get_ports {in_data[3]}]
set_max_transition 3 [get_ports {in_data[2]}]
set_max_transition 3 [get_ports {in_data[1]}]
set_max_transition 3 [get_ports {in_data[0]}]
create_clock [get_ports clk]  -period 4.3  -waveform {0 2.15}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 2.15  [get_ports in_valid]
set_input_delay -clock clk  -min 0  [get_ports in_valid]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[63]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[63]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[62]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[62]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[61]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[61]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[60]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[60]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[59]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[59]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[58]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[58]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[57]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[57]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[56]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[56]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[55]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[55]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[54]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[54]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[53]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[53]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[52]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[52]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[51]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[51]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[50]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[50]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[49]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[49]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[48]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[48]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[47]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[47]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[46]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[46]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[45]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[45]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[44]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[44]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[43]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[43]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[42]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[42]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[41]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[41]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[40]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[40]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[39]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[39]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[38]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[38]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[37]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[37]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[36]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[36]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[35]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[35]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[34]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[34]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[33]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[33]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[32]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[32]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[31]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[31]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[30]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[30]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[29]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[29]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[28]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[28]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[27]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[27]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[26]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[26]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[25]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[25]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[24]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[24]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[23]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[23]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[22]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[22]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[21]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[21]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[20]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[20]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[19]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[19]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[18]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[18]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[17]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[17]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[16]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[16]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[15]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[15]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[14]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[14]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[13]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[13]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[12]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[12]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[11]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[11]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[10]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[10]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[9]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[9]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[8]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[8]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[7]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[7]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[6]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[6]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[5]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[5]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[4]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[4]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[3]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[3]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[2]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[1]}]
set_input_delay -clock clk  -max 2.15  [get_ports {in_data[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_data[0]}]
set_output_delay -clock clk  -max 2.15  [get_ports out_valid]
set_output_delay -clock clk  -min 0  [get_ports out_valid]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[19]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[19]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[18]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[18]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[17]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[17]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[16]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[16]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[15]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[15]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[14]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[14]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[13]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[13]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[12]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[12]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[11]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[11]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[10]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[10]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[9]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[9]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[8]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[8]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[7]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[7]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[6]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[6]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[5]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[5]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[4]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[4]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[3]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[3]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[2]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[2]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[1]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[1]}]
set_output_delay -clock clk  -max 2.15  [get_ports {out_data[0]}]
set_output_delay -clock clk  -min 0  [get_ports {out_data[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {in_data[63]}]
set_input_transition -min 0.5  [get_ports {in_data[63]}]
set_input_transition -max 0.5  [get_ports {in_data[62]}]
set_input_transition -min 0.5  [get_ports {in_data[62]}]
set_input_transition -max 0.5  [get_ports {in_data[61]}]
set_input_transition -min 0.5  [get_ports {in_data[61]}]
set_input_transition -max 0.5  [get_ports {in_data[60]}]
set_input_transition -min 0.5  [get_ports {in_data[60]}]
set_input_transition -max 0.5  [get_ports {in_data[59]}]
set_input_transition -min 0.5  [get_ports {in_data[59]}]
set_input_transition -max 0.5  [get_ports {in_data[58]}]
set_input_transition -min 0.5  [get_ports {in_data[58]}]
set_input_transition -max 0.5  [get_ports {in_data[57]}]
set_input_transition -min 0.5  [get_ports {in_data[57]}]
set_input_transition -max 0.5  [get_ports {in_data[56]}]
set_input_transition -min 0.5  [get_ports {in_data[56]}]
set_input_transition -max 0.5  [get_ports {in_data[55]}]
set_input_transition -min 0.5  [get_ports {in_data[55]}]
set_input_transition -max 0.5  [get_ports {in_data[54]}]
set_input_transition -min 0.5  [get_ports {in_data[54]}]
set_input_transition -max 0.5  [get_ports {in_data[53]}]
set_input_transition -min 0.5  [get_ports {in_data[53]}]
set_input_transition -max 0.5  [get_ports {in_data[52]}]
set_input_transition -min 0.5  [get_ports {in_data[52]}]
set_input_transition -max 0.5  [get_ports {in_data[51]}]
set_input_transition -min 0.5  [get_ports {in_data[51]}]
set_input_transition -max 0.5  [get_ports {in_data[50]}]
set_input_transition -min 0.5  [get_ports {in_data[50]}]
set_input_transition -max 0.5  [get_ports {in_data[49]}]
set_input_transition -min 0.5  [get_ports {in_data[49]}]
set_input_transition -max 0.5  [get_ports {in_data[48]}]
set_input_transition -min 0.5  [get_ports {in_data[48]}]
set_input_transition -max 0.5  [get_ports {in_data[47]}]
set_input_transition -min 0.5  [get_ports {in_data[47]}]
set_input_transition -max 0.5  [get_ports {in_data[46]}]
set_input_transition -min 0.5  [get_ports {in_data[46]}]
set_input_transition -max 0.5  [get_ports {in_data[45]}]
set_input_transition -min 0.5  [get_ports {in_data[45]}]
set_input_transition -max 0.5  [get_ports {in_data[44]}]
set_input_transition -min 0.5  [get_ports {in_data[44]}]
set_input_transition -max 0.5  [get_ports {in_data[43]}]
set_input_transition -min 0.5  [get_ports {in_data[43]}]
set_input_transition -max 0.5  [get_ports {in_data[42]}]
set_input_transition -min 0.5  [get_ports {in_data[42]}]
set_input_transition -max 0.5  [get_ports {in_data[41]}]
set_input_transition -min 0.5  [get_ports {in_data[41]}]
set_input_transition -max 0.5  [get_ports {in_data[40]}]
set_input_transition -min 0.5  [get_ports {in_data[40]}]
set_input_transition -max 0.5  [get_ports {in_data[39]}]
set_input_transition -min 0.5  [get_ports {in_data[39]}]
set_input_transition -max 0.5  [get_ports {in_data[38]}]
set_input_transition -min 0.5  [get_ports {in_data[38]}]
set_input_transition -max 0.5  [get_ports {in_data[37]}]
set_input_transition -min 0.5  [get_ports {in_data[37]}]
set_input_transition -max 0.5  [get_ports {in_data[36]}]
set_input_transition -min 0.5  [get_ports {in_data[36]}]
set_input_transition -max 0.5  [get_ports {in_data[35]}]
set_input_transition -min 0.5  [get_ports {in_data[35]}]
set_input_transition -max 0.5  [get_ports {in_data[34]}]
set_input_transition -min 0.5  [get_ports {in_data[34]}]
set_input_transition -max 0.5  [get_ports {in_data[33]}]
set_input_transition -min 0.5  [get_ports {in_data[33]}]
set_input_transition -max 0.5  [get_ports {in_data[32]}]
set_input_transition -min 0.5  [get_ports {in_data[32]}]
set_input_transition -max 0.5  [get_ports {in_data[31]}]
set_input_transition -min 0.5  [get_ports {in_data[31]}]
set_input_transition -max 0.5  [get_ports {in_data[30]}]
set_input_transition -min 0.5  [get_ports {in_data[30]}]
set_input_transition -max 0.5  [get_ports {in_data[29]}]
set_input_transition -min 0.5  [get_ports {in_data[29]}]
set_input_transition -max 0.5  [get_ports {in_data[28]}]
set_input_transition -min 0.5  [get_ports {in_data[28]}]
set_input_transition -max 0.5  [get_ports {in_data[27]}]
set_input_transition -min 0.5  [get_ports {in_data[27]}]
set_input_transition -max 0.5  [get_ports {in_data[26]}]
set_input_transition -min 0.5  [get_ports {in_data[26]}]
set_input_transition -max 0.5  [get_ports {in_data[25]}]
set_input_transition -min 0.5  [get_ports {in_data[25]}]
set_input_transition -max 0.5  [get_ports {in_data[24]}]
set_input_transition -min 0.5  [get_ports {in_data[24]}]
set_input_transition -max 0.5  [get_ports {in_data[23]}]
set_input_transition -min 0.5  [get_ports {in_data[23]}]
set_input_transition -max 0.5  [get_ports {in_data[22]}]
set_input_transition -min 0.5  [get_ports {in_data[22]}]
set_input_transition -max 0.5  [get_ports {in_data[21]}]
set_input_transition -min 0.5  [get_ports {in_data[21]}]
set_input_transition -max 0.5  [get_ports {in_data[20]}]
set_input_transition -min 0.5  [get_ports {in_data[20]}]
set_input_transition -max 0.5  [get_ports {in_data[19]}]
set_input_transition -min 0.5  [get_ports {in_data[19]}]
set_input_transition -max 0.5  [get_ports {in_data[18]}]
set_input_transition -min 0.5  [get_ports {in_data[18]}]
set_input_transition -max 0.5  [get_ports {in_data[17]}]
set_input_transition -min 0.5  [get_ports {in_data[17]}]
set_input_transition -max 0.5  [get_ports {in_data[16]}]
set_input_transition -min 0.5  [get_ports {in_data[16]}]
set_input_transition -max 0.5  [get_ports {in_data[15]}]
set_input_transition -min 0.5  [get_ports {in_data[15]}]
set_input_transition -max 0.5  [get_ports {in_data[14]}]
set_input_transition -min 0.5  [get_ports {in_data[14]}]
set_input_transition -max 0.5  [get_ports {in_data[13]}]
set_input_transition -min 0.5  [get_ports {in_data[13]}]
set_input_transition -max 0.5  [get_ports {in_data[12]}]
set_input_transition -min 0.5  [get_ports {in_data[12]}]
set_input_transition -max 0.5  [get_ports {in_data[11]}]
set_input_transition -min 0.5  [get_ports {in_data[11]}]
set_input_transition -max 0.5  [get_ports {in_data[10]}]
set_input_transition -min 0.5  [get_ports {in_data[10]}]
set_input_transition -max 0.5  [get_ports {in_data[9]}]
set_input_transition -min 0.5  [get_ports {in_data[9]}]
set_input_transition -max 0.5  [get_ports {in_data[8]}]
set_input_transition -min 0.5  [get_ports {in_data[8]}]
set_input_transition -max 0.5  [get_ports {in_data[7]}]
set_input_transition -min 0.5  [get_ports {in_data[7]}]
set_input_transition -max 0.5  [get_ports {in_data[6]}]
set_input_transition -min 0.5  [get_ports {in_data[6]}]
set_input_transition -max 0.5  [get_ports {in_data[5]}]
set_input_transition -min 0.5  [get_ports {in_data[5]}]
set_input_transition -max 0.5  [get_ports {in_data[4]}]
set_input_transition -min 0.5  [get_ports {in_data[4]}]
set_input_transition -max 0.5  [get_ports {in_data[3]}]
set_input_transition -min 0.5  [get_ports {in_data[3]}]
set_input_transition -max 0.5  [get_ports {in_data[2]}]
set_input_transition -min 0.5  [get_ports {in_data[2]}]
set_input_transition -max 0.5  [get_ports {in_data[1]}]
set_input_transition -min 0.5  [get_ports {in_data[1]}]
set_input_transition -max 0.5  [get_ports {in_data[0]}]
set_input_transition -min 0.5  [get_ports {in_data[0]}]
