 
****************************************
Report : resources
Design : AMED
Version: U-2022.12
Date   : Tue Jun 16 03:53:11 2026
****************************************


Resource Report for this hierarchy in file ../01_RTL/AMED.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| add_x_1        | DW01_inc       | width=4    | add_25 (AMED.v:25)         |
| ne_x_13        | DW_cmp         | width=16   | ne_96 (AMED.v:96)          |
| ne_x_14        | DW_cmp         | width=16   | ne_97 (AMED.v:97)          |
| sub_x_17       | DW01_sub       | width=17   | sub_102 (AMED.v:102)       |
| lte_x_19       | DW_cmp         | width=4    | lte_107 (AMED.v:107)       |
|                |                |            | lte_52 (AMED.v:52)         |
=============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| add_x_1            | DW01_inc         | apparch (area)     |                |
| ne_x_13            | DW_cmp           | apparch (area)     |                |
| ne_x_14            | DW_cmp           | apparch (area)     |                |
| sub_x_17           | DW01_sub         | pparch (area,speed)                 |
| lte_x_19           | DW_cmp           | apparch (area)     |                |
===============================================================================

1
