 
****************************************
Report : resources
Design : FIFO
Version: U-2022.12
Date   : Tue May 19 04:09:31 2026
****************************************

Resource Sharing Report for design FIFO in file ../01_RTL/FIFO.v

===============================================================================
|          |              |            | Contained     |                      |
| Resource | Module       | Parameters | Resources     | Contained Operations |
===============================================================================
| r369     | DW01_inc     | width=6    |               | add_28_S2            |
| r371     | DW01_inc     | width=6    |               | add_36_S2            |
| r373     | DW_cmp       | width=6    |               | eq_71                |
| r375     | DW_cmp       | width=5    |               | eq_73                |
===============================================================================


No implementations to report
1
