###################################################################

# Created by write_sdc on Tue May 19 04:09:32 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0.05 [get_ports {r_data[15]}]
set_load -pin_load 0.05 [get_ports {r_data[14]}]
set_load -pin_load 0.05 [get_ports {r_data[13]}]
set_load -pin_load 0.05 [get_ports {r_data[12]}]
set_load -pin_load 0.05 [get_ports {r_data[11]}]
set_load -pin_load 0.05 [get_ports {r_data[10]}]
set_load -pin_load 0.05 [get_ports {r_data[9]}]
set_load -pin_load 0.05 [get_ports {r_data[8]}]
set_load -pin_load 0.05 [get_ports {r_data[7]}]
set_load -pin_load 0.05 [get_ports {r_data[6]}]
set_load -pin_load 0.05 [get_ports {r_data[5]}]
set_load -pin_load 0.05 [get_ports {r_data[4]}]
set_load -pin_load 0.05 [get_ports {r_data[3]}]
set_load -pin_load 0.05 [get_ports {r_data[2]}]
set_load -pin_load 0.05 [get_ports {r_data[1]}]
set_load -pin_load 0.05 [get_ports {r_data[0]}]
set_load -pin_load 0.05 [get_ports full]
set_load -pin_load 0.05 [get_ports empty]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports w_en]
set_max_capacitance 0.15 [get_ports {w_data[15]}]
set_max_capacitance 0.15 [get_ports {w_data[14]}]
set_max_capacitance 0.15 [get_ports {w_data[13]}]
set_max_capacitance 0.15 [get_ports {w_data[12]}]
set_max_capacitance 0.15 [get_ports {w_data[11]}]
set_max_capacitance 0.15 [get_ports {w_data[10]}]
set_max_capacitance 0.15 [get_ports {w_data[9]}]
set_max_capacitance 0.15 [get_ports {w_data[8]}]
set_max_capacitance 0.15 [get_ports {w_data[7]}]
set_max_capacitance 0.15 [get_ports {w_data[6]}]
set_max_capacitance 0.15 [get_ports {w_data[5]}]
set_max_capacitance 0.15 [get_ports {w_data[4]}]
set_max_capacitance 0.15 [get_ports {w_data[3]}]
set_max_capacitance 0.15 [get_ports {w_data[2]}]
set_max_capacitance 0.15 [get_ports {w_data[1]}]
set_max_capacitance 0.15 [get_ports {w_data[0]}]
set_max_capacitance 0.15 [get_ports r_en]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports w_en]
set_max_fanout 10 [get_ports {w_data[15]}]
set_max_fanout 10 [get_ports {w_data[14]}]
set_max_fanout 10 [get_ports {w_data[13]}]
set_max_fanout 10 [get_ports {w_data[12]}]
set_max_fanout 10 [get_ports {w_data[11]}]
set_max_fanout 10 [get_ports {w_data[10]}]
set_max_fanout 10 [get_ports {w_data[9]}]
set_max_fanout 10 [get_ports {w_data[8]}]
set_max_fanout 10 [get_ports {w_data[7]}]
set_max_fanout 10 [get_ports {w_data[6]}]
set_max_fanout 10 [get_ports {w_data[5]}]
set_max_fanout 10 [get_ports {w_data[4]}]
set_max_fanout 10 [get_ports {w_data[3]}]
set_max_fanout 10 [get_ports {w_data[2]}]
set_max_fanout 10 [get_ports {w_data[1]}]
set_max_fanout 10 [get_ports {w_data[0]}]
set_max_fanout 10 [get_ports r_en]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports w_en]
set_max_transition 3 [get_ports {w_data[15]}]
set_max_transition 3 [get_ports {w_data[14]}]
set_max_transition 3 [get_ports {w_data[13]}]
set_max_transition 3 [get_ports {w_data[12]}]
set_max_transition 3 [get_ports {w_data[11]}]
set_max_transition 3 [get_ports {w_data[10]}]
set_max_transition 3 [get_ports {w_data[9]}]
set_max_transition 3 [get_ports {w_data[8]}]
set_max_transition 3 [get_ports {w_data[7]}]
set_max_transition 3 [get_ports {w_data[6]}]
set_max_transition 3 [get_ports {w_data[5]}]
set_max_transition 3 [get_ports {w_data[4]}]
set_max_transition 3 [get_ports {w_data[3]}]
set_max_transition 3 [get_ports {w_data[2]}]
set_max_transition 3 [get_ports {w_data[1]}]
set_max_transition 3 [get_ports {w_data[0]}]
set_max_transition 3 [get_ports r_en]
create_clock [get_ports clk]  -period 20  -waveform {0 10}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 6  [get_ports w_en]
set_input_delay -clock clk  -min 0  [get_ports w_en]
set_input_delay -clock clk  -max 6  [get_ports {w_data[15]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[15]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[14]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[14]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[13]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[13]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[12]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[12]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[11]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[11]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[10]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[10]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[9]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[9]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[8]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[8]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[7]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[7]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[6]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[6]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[5]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[5]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[4]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[4]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[3]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[3]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[2]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[2]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[1]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[1]}]
set_input_delay -clock clk  -max 6  [get_ports {w_data[0]}]
set_input_delay -clock clk  -min 0  [get_ports {w_data[0]}]
set_input_delay -clock clk  -max 6  [get_ports r_en]
set_input_delay -clock clk  -min 0  [get_ports r_en]
set_output_delay -clock clk  -max 6  [get_ports {r_data[15]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[15]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[14]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[14]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[13]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[13]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[12]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[12]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[11]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[11]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[10]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[10]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[9]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[9]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[8]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[8]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[7]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[7]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[6]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[6]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[5]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[5]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[4]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[4]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[3]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[3]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[2]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[2]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[1]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[1]}]
set_output_delay -clock clk  -max 6  [get_ports {r_data[0]}]
set_output_delay -clock clk  -min 0  [get_ports {r_data[0]}]
set_output_delay -clock clk  -max 6  [get_ports full]
set_output_delay -clock clk  -min 0  [get_ports full]
set_output_delay -clock clk  -max 6  [get_ports empty]
set_output_delay -clock clk  -min 0  [get_ports empty]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports w_en]
set_input_transition -min 0.5  [get_ports w_en]
set_input_transition -max 0.5  [get_ports {w_data[15]}]
set_input_transition -min 0.5  [get_ports {w_data[15]}]
set_input_transition -max 0.5  [get_ports {w_data[14]}]
set_input_transition -min 0.5  [get_ports {w_data[14]}]
set_input_transition -max 0.5  [get_ports {w_data[13]}]
set_input_transition -min 0.5  [get_ports {w_data[13]}]
set_input_transition -max 0.5  [get_ports {w_data[12]}]
set_input_transition -min 0.5  [get_ports {w_data[12]}]
set_input_transition -max 0.5  [get_ports {w_data[11]}]
set_input_transition -min 0.5  [get_ports {w_data[11]}]
set_input_transition -max 0.5  [get_ports {w_data[10]}]
set_input_transition -min 0.5  [get_ports {w_data[10]}]
set_input_transition -max 0.5  [get_ports {w_data[9]}]
set_input_transition -min 0.5  [get_ports {w_data[9]}]
set_input_transition -max 0.5  [get_ports {w_data[8]}]
set_input_transition -min 0.5  [get_ports {w_data[8]}]
set_input_transition -max 0.5  [get_ports {w_data[7]}]
set_input_transition -min 0.5  [get_ports {w_data[7]}]
set_input_transition -max 0.5  [get_ports {w_data[6]}]
set_input_transition -min 0.5  [get_ports {w_data[6]}]
set_input_transition -max 0.5  [get_ports {w_data[5]}]
set_input_transition -min 0.5  [get_ports {w_data[5]}]
set_input_transition -max 0.5  [get_ports {w_data[4]}]
set_input_transition -min 0.5  [get_ports {w_data[4]}]
set_input_transition -max 0.5  [get_ports {w_data[3]}]
set_input_transition -min 0.5  [get_ports {w_data[3]}]
set_input_transition -max 0.5  [get_ports {w_data[2]}]
set_input_transition -min 0.5  [get_ports {w_data[2]}]
set_input_transition -max 0.5  [get_ports {w_data[1]}]
set_input_transition -min 0.5  [get_ports {w_data[1]}]
set_input_transition -max 0.5  [get_ports {w_data[0]}]
set_input_transition -min 0.5  [get_ports {w_data[0]}]
set_input_transition -max 0.5  [get_ports r_en]
set_input_transition -min 0.5  [get_ports r_en]
